DATA = {
    "AF": {
        "official_name": "Afghanistan",
        "name_en": "Afghanistan",
        "name_ge": "ავღანეთი",
        "alpha_3_code": "AFG",
        "numeric_code": 4,
        "flag": "🇦🇫",
    },
    "AL": {
        "official_name": "Albania",
        "name_en": "Albania",
        "name_ge": "ალბანეთი",
        "alpha_3_code": "ALB",
        "numeric_code": 8,
        "flag": "🇦🇱",
    },
    "DZ": {
        "official_name": "Algeria",
        "name_en": "Algeria",
        "name_ge": "ალჟირი",
        "alpha_3_code": "DZA",
        "numeric_code": 12,
        "flag": "🇩🇿",
    },
    "AS": {
        "official_name": "American Samoa",
        "name_en": "American Samoa",
        "name_ge": "ამერიკის სამოა",
        "alpha_3_code": "ASM",
        "numeric_code": 16,
        "flag": "🇦🇸",
    },
    "AD": {
        "official_name": "Andorra",
        "name_en": "Andorra",
        "name_ge": "ანდორა",
        "alpha_3_code": "AND",
        "numeric_code": 20,
        "flag": "🇦🇩",
    },
    "AO": {
        "official_name": "Angola",
        "name_en": "Angola",
        "name_ge": "ანგოლა",
        "alpha_3_code": "AGO",
        "numeric_code": 24,
        "flag": "🇦🇴",
    },
    "AI": {
        "official_name": "Anguilla",
        "name_en": "Anguilla",
        "name_ge": "ანგილა",
        "alpha_3_code": "AIA",
        "numeric_code": 660,
        "flag": "🇦🇮",
    },
    "AQ": {
        "official_name": "Antarctica",
        "name_en": "Antarctica",
        "name_ge": "ანტარქტიდა",
        "alpha_3_code": "ATA",
        "numeric_code": 10,
        "flag": "🇦🇶",
    },
    "AG": {
        "official_name": "Antigua and Barbuda",
        "name_en": "Antigua and Barbuda",
        "name_ge": "ანტიგუა და ბარბუდა",
        "alpha_3_code": "ATG",
        "numeric_code": 28,
        "flag": "🇦🇬",
    },
    "AR": {
        "official_name": "Argentina",
        "name_en": "Argentina",
        "name_ge": "არგენტინა",
        "alpha_3_code": "ARG",
        "numeric_code": 32,
        "flag": "🇦🇷",
    },
    "AM": {
        "official_name": "Armenia",
        "name_en": "Armenia",
        "name_ge": "სომხეთი",
        "alpha_3_code": "ARM",
        "numeric_code": 51,
        "flag": "🇦🇲",
    },
    "AW": {
        "official_name": "Aruba",
        "name_en": "Aruba",
        "name_ge": "არუბა",
        "alpha_3_code": "ABW",
        "numeric_code": 533,
        "flag": "🇦🇼",
    },
    "AU": {
        "official_name": "Australia",
        "name_en": "Australia",
        "name_ge": "ავსტრალია",
        "alpha_3_code": "AUS",
        "numeric_code": 36,
        "flag": "🇦🇺",
    },
    "AT": {
        "official_name": "Austria",
        "name_en": "Austria",
        "name_ge": "ავსტრია",
        "alpha_3_code": "AUT",
        "numeric_code": 40,
        "flag": "🇦🇹",
    },
    "AZ": {
        "official_name": "Azerbaijan",
        "name_en": "Azerbaijan",
        "name_ge": "აზერბაიჯანი",
        "alpha_3_code": "AZE",
        "numeric_code": 31,
        "flag": "🇦🇿",
    },
    "BS": {
        "official_name": "Bahamas (the)",
        "name_en": "Bahamas",
        "name_ge": "ბაჰამის კუნძულები",
        "alpha_3_code": "BHS",
        "numeric_code": 44,
        "flag": "🇧🇸",
    },
    "BH": {
        "official_name": "Bahrain",
        "name_en": "Bahrain",
        "name_ge": "ბაჰრეინი",
        "alpha_3_code": "BHR",
        "numeric_code": 48,
        "flag": "🇧🇭",
    },
    "BD": {
        "official_name": "Bangladesh",
        "name_en": "Bangladesh",
        "name_ge": "ბანგლადეში",
        "alpha_3_code": "BGD",
        "numeric_code": 50,
        "flag": "🇧🇩",
    },
    "BB": {
        "official_name": "Barbados",
        "name_en": "Barbados",
        "name_ge": "ბარბადოსი",
        "alpha_3_code": "BRB",
        "numeric_code": 52,
        "flag": "🇧🇧",
    },
    "BY": {
        "official_name": "Belarus",
        "name_en": "Belarus",
        "name_ge": "ბელორუსია",
        "alpha_3_code": "BLR",
        "numeric_code": 112,
        "flag": "🇧🇾",
    },
    "BE": {
        "official_name": "Belgium",
        "name_en": "Belgium",
        "name_ge": "ბელგია",
        "alpha_3_code": "BEL",
        "numeric_code": 56,
        "flag": "🇧🇪",
    },
    "BZ": {
        "official_name": "Belize",
        "name_en": "Belize",
        "name_ge": "ბელიზი",
        "alpha_3_code": "BLZ",
        "numeric_code": 84,
        "flag": "🇧🇿",
    },
    "BJ": {
        "official_name": "Benin",
        "name_en": "Benin",
        "name_ge": "ბენინი",
        "alpha_3_code": "BEN",
        "numeric_code": 204,
        "flag": "🇧🇯",
    },
    "BM": {
        "official_name": "Bermuda",
        "name_en": "Bermuda",
        "name_ge": "ბერმუდი",
        "alpha_3_code": "BMU",
        "numeric_code": 60,
        "flag": "🇧🇲",
    },
    "BT": {
        "official_name": "Bhutan",
        "name_en": "Bhutan",
        "name_ge": "ბუტანი",
        "alpha_3_code": "BTN",
        "numeric_code": 64,
        "flag": "🇧🇹",
    },
    "BO": {
        "official_name": "Bolivia (Plurinational State of)",
        "name_en": "Bolivia",
        "name_ge": "ბოლივია",
        "alpha_3_code": "BOL",
        "numeric_code": 68,
        "flag": "🇧🇴",
    },
    "BQ": {
        "official_name": "Bonaire, Sint Eustatius and Saba",
        "name_en": "Bonaire, Sint Eustatius and Saba",
        "name_ge": "ბონერი, სინტ ევსტათიუსი და საბა",
        "alpha_3_code": "BES",
        "numeric_code": 535,
        "flag": None,
    },
    "BA": {
        "official_name": "Bosnia and Herzegovina",
        "name_en": "Bosnia and Herzegovina",
        "name_ge": "ბოსნია და ჰერცოგოვინა",
        "alpha_3_code": "BIH",
        "numeric_code": 70,
        "flag": "🇧🇦",
    },
    "BW": {
        "official_name": "Botswana",
        "name_en": "Botswana",
        "name_ge": "ბოტსვანა",
        "alpha_3_code": "BWA",
        "numeric_code": 72,
        "flag": "🇧🇼",
    },
    "BV": {
        "official_name": "Bouvet Island",
        "name_en": "Bouvet Island",
        "name_ge": "ბუვეს კუნძული",
        "alpha_3_code": "BVT",
        "numeric_code": 74,
        "flag": "🇧🇻",
    },
    "BR": {
        "official_name": "Brazil",
        "name_en": "Brazil",
        "name_ge": "ბრაზილია",
        "alpha_3_code": "BRA",
        "numeric_code": 76,
        "flag": "🇧🇷",
    },
    "IO": {
        "official_name": "British Indian Ocean Territory (the)",
        "name_en": "British Indian Ocean Territory",
        "name_ge": "ბრიტანეთის ინდოეთის ოკეანის ტერიტორია",
        "alpha_3_code": "IOT",
        "numeric_code": 86,
        "flag": "🇮🇴",
    },
    "BN": {
        "official_name": "Brunei Darussalam",
        "name_en": "Brunei Darussalam",
        "name_ge": "ბრუნეი დარუსალამი",
        "alpha_3_code": "BRN",
        "numeric_code": 96,
        "flag": "🇧🇳",
    },
    "BG": {
        "official_name": "Bulgaria",
        "name_en": "Bulgaria",
        "name_ge": "ბულგარეთი",
        "alpha_3_code": "BGR",
        "numeric_code": 100,
        "flag": "🇧🇬",
    },
    "BF": {
        "official_name": "Burkina Faso",
        "name_en": "Burkina Faso",
        "name_ge": "ბურკინა ფასო",
        "alpha_3_code": "BFA",
        "numeric_code": 854,
        "flag": "🇧🇫",
    },
    "BI": {
        "official_name": "Burundi",
        "name_en": "Burundi",
        "name_ge": "ბურუნდი",
        "alpha_3_code": "BDI",
        "numeric_code": 108,
        "flag": "🇧🇮",
    },
    "CV": {
        "official_name": "Cabo Verde",
        "name_en": "Cabo Verde",
        "name_ge": "კაბო ვერდე",
        "alpha_3_code": "CPV",
        "numeric_code": 132,
        "flag": "🇨🇻",
    },
    "KH": {
        "official_name": "Cambodia",
        "name_en": "Cambodia",
        "name_ge": "კამბოჯა",
        "alpha_3_code": "KHM",
        "numeric_code": 116,
        "flag": "🇰🇭",
    },
    "CM": {
        "official_name": "Cameroon",
        "name_en": "Cameroon",
        "name_ge": "კამერუნი",
        "alpha_3_code": "CMR",
        "numeric_code": 120,
        "flag": "🇨🇲",
    },
    "CA": {
        "official_name": "Canada",
        "name_en": "Canada",
        "name_ge": "კანადა",
        "alpha_3_code": "CAN",
        "numeric_code": 124,
        "flag": "🇨🇦",
    },
    "KY": {
        "official_name": "Cayman Islands (the)",
        "name_en": "Cayman Islands",
        "name_ge": "კაიმანის კუნძულები",
        "alpha_3_code": "CYM",
        "numeric_code": 136,
        "flag": "🇰🇾",
    },
    "CF": {
        "official_name": "Central African Republic (the)",
        "name_en": "Central African Republic",
        "name_ge": "ცენტრალური აფრიკის რესპუბლიკა",
        "alpha_3_code": "CAF",
        "numeric_code": 140,
        "flag": "🇨🇫",
    },
    "TD": {
        "official_name": "Chad",
        "name_en": "Chad",
        "name_ge": "ჩადი",
        "alpha_3_code": "TCD",
        "numeric_code": 148,
        "flag": "🇹🇩",
    },
    "CL": {
        "official_name": "Chile",
        "name_en": "Chile",
        "name_ge": "ჩილე",
        "alpha_3_code": "CHL",
        "numeric_code": 152,
        "flag": "🇨🇱",
    },
    "CN": {
        "official_name": "China",
        "name_en": "China",
        "name_ge": "ჩინეთი",
        "alpha_3_code": "CHN",
        "numeric_code": 156,
        "flag": "🇨🇳",
    },
    "CX": {
        "official_name": "Christmas Island",
        "name_en": "Christmas Island",
        "name_ge": "შობის კუნძული",
        "alpha_3_code": "CXR",
        "numeric_code": 162,
        "flag": "🇨🇽",
    },
    "CC": {
        "official_name": "Cocos (Keeling) Islands (the)",
        "name_en": "Cocos (Keeling) Islands",
        "name_ge": "კოკოსის (კილინგის) კუნძულები",
        "alpha_3_code": "CCK",
        "numeric_code": 166,
        "flag": "🇨🇨",
    },
    "CO": {
        "official_name": "Colombia",
        "name_en": "Colombia",
        "name_ge": "კოლუმბია",
        "alpha_3_code": "COL",
        "numeric_code": 170,
        "flag": "🇨🇴",
    },
    "KM": {
        "official_name": "Comoros (the)",
        "name_en": "Comoros",
        "name_ge": "კომორის კუნძულები",
        "alpha_3_code": "COM",
        "numeric_code": 174,
        "flag": "🇰🇲",
    },
    "CD": {
        "official_name": "Congo (the Democratic Republic of the)",
        "name_en": "Congo",
        "name_ge": "კონგო",
        "alpha_3_code": "COD",
        "numeric_code": 180,
        "flag": "🇨🇩",
    },
    "CG": {
        "official_name": "Congo (the)",
        "name_en": "Congo",
        "name_ge": "კონგო",
        "alpha_3_code": "COG",
        "numeric_code": 178,
        "flag": "🇨🇬",
    },
    "CK": {
        "official_name": "Cook Islands (the)",
        "name_en": "Cook Islands",
        "name_ge": "კუკის კუნძულები",
        "alpha_3_code": "COK",
        "numeric_code": 184,
        "flag": "🇨🇰",
    },
    "CR": {
        "official_name": "Costa Rica",
        "name_en": "Costa Rica",
        "name_ge": "კოსტა - რიკა",
        "alpha_3_code": "CRI",
        "numeric_code": 188,
        "flag": "🇨🇷",
    },
    "HR": {
        "official_name": "Croatia",
        "name_en": "Croatia",
        "name_ge": "ხორვატია",
        "alpha_3_code": "HRV",
        "numeric_code": 191,
        "flag": "🇭🇷",
    },
    "CU": {
        "official_name": "Cuba",
        "name_en": "Cuba",
        "name_ge": "კუბა",
        "alpha_3_code": "CUB",
        "numeric_code": 192,
        "flag": "🇨🇺",
    },
    "CW": {
        "official_name": "Curaçao",
        "name_en": "Curaçao",
        "name_ge": "კურასაო",
        "alpha_3_code": "CUW",
        "numeric_code": 531,
        "flag": "🇨🇼",
    },
    "CY": {
        "official_name": "Cyprus",
        "name_en": "Cyprus",
        "name_ge": "კვიპროსი",
        "alpha_3_code": "CYP",
        "numeric_code": 196,
        "flag": "🇨🇾",
    },
    "CZ": {
        "official_name": "Czechia",
        "name_en": "Czechia",
        "name_ge": "ჩეხეთი",
        "alpha_3_code": "CZE",
        "numeric_code": 203,
        "flag": "🇨🇿",
    },
    "CI": {
        "official_name": "Côte d'Ivoire",
        "name_en": "Côte d'Ivoire",
        "name_ge": "კოტ დ'ივუარი",
        "alpha_3_code": "CIV",
        "numeric_code": 384,
        "flag": "🇨🇮",
    },
    "DK": {
        "official_name": "Denmark",
        "name_en": "Denmark",
        "name_ge": "დანია",
        "alpha_3_code": "DNK",
        "numeric_code": 208,
        "flag": "🇩🇰",
    },
    "DJ": {
        "official_name": "Djibouti",
        "name_en": "Djibouti",
        "name_ge": "ჯიბუტი",
        "alpha_3_code": "DJI",
        "numeric_code": 262,
        "flag": "🇩🇯",
    },
    "DM": {
        "official_name": "Dominica",
        "name_en": "Dominica",
        "name_ge": "დომინიკა",
        "alpha_3_code": "DMA",
        "numeric_code": 212,
        "flag": "🇩🇲",
    },
    "DO": {
        "official_name": "Dominican Republic (the)",
        "name_en": "Dominican Republic",
        "name_ge": "დომინიკის რესპუბლიკა",
        "alpha_3_code": "DOM",
        "numeric_code": 214,
        "flag": "🇩🇴",
    },
    "EC": {
        "official_name": "Ecuador",
        "name_en": "Ecuador",
        "name_ge": "ეკვადორი",
        "alpha_3_code": "ECU",
        "numeric_code": 218,
        "flag": "🇪🇨",
    },
    "EG": {
        "official_name": "Egypt",
        "name_en": "Egypt",
        "name_ge": "ეგვიპტე",
        "alpha_3_code": "EGY",
        "numeric_code": 818,
        "flag": "🇪🇬",
    },
    "SV": {
        "official_name": "El Salvador",
        "name_en": "El Salvador",
        "name_ge": "ელ სალვადორი",
        "alpha_3_code": "SLV",
        "numeric_code": 222,
        "flag": "🇸🇻",
    },
    "GQ": {
        "official_name": "Equatorial Guinea",
        "name_en": "Equatorial Guinea",
        "name_ge": "ეკვატორული გვინეა",
        "alpha_3_code": "GNQ",
        "numeric_code": 226,
        "flag": "🇬🇶",
    },
    "ER": {
        "official_name": "Eritrea",
        "name_en": "Eritrea",
        "name_ge": "ერიტრეა",
        "alpha_3_code": "ERI",
        "numeric_code": 232,
        "flag": "🇪🇷",
    },
    "EE": {
        "official_name": "Estonia",
        "name_en": "Estonia",
        "name_ge": "ესტონეთი",
        "alpha_3_code": "EST",
        "numeric_code": 233,
        "flag": "🇪🇪",
    },
    "SZ": {
        "official_name": "Eswatini",
        "name_en": "Eswatini",
        "name_ge": "ესვატინი",
        "alpha_3_code": "SWZ",
        "numeric_code": 748,
        "flag": "🇸🇿",
    },
    "ET": {
        "official_name": "Ethiopia",
        "name_en": "Ethiopia",
        "name_ge": "ეთიოპია",
        "alpha_3_code": "ETH",
        "numeric_code": 231,
        "flag": "🇪🇹",
    },
    "FK": {
        "official_name": "Falkland Islands (the) [Malvinas]",
        "name_en": "Falkland Islands [Malvinas]",
        "name_ge": "ფოლკლენდის კუნძულები [მალვინები]",
        "alpha_3_code": "FLK",
        "numeric_code": 238,
        "flag": "🇫🇰",
    },
    "FO": {
        "official_name": "Faroe Islands (the)",
        "name_en": "Faroe Islands",
        "name_ge": "ფარერის კუნძულები",
        "alpha_3_code": "FRO",
        "numeric_code": 234,
        "flag": "🇫🇴",
    },
    "FJ": {
        "official_name": "Fiji",
        "name_en": "Fiji",
        "name_ge": "ფიჯი",
        "alpha_3_code": "FJI",
        "numeric_code": 242,
        "flag": "🇫🇯",
    },
    "FI": {
        "official_name": "Finland",
        "name_en": "Finland",
        "name_ge": "ფინეთი",
        "alpha_3_code": "FIN",
        "numeric_code": 246,
        "flag": "🇫🇮",
    },
    "FR": {
        "official_name": "France",
        "name_en": "France",
        "name_ge": "საფრანგეთი",
        "alpha_3_code": "FRA",
        "numeric_code": 250,
        "flag": "🇫🇷",
    },
    "GF": {
        "official_name": "French Guiana",
        "name_en": "French Guiana",
        "name_ge": "ფრანგული გუიანა",
        "alpha_3_code": "GUF",
        "numeric_code": 254,
        "flag": "🇬🇫",
    },
    "PF": {
        "official_name": "French Polynesia",
        "name_en": "French Polynesia",
        "name_ge": "ფრანგული პოლინეზია",
        "alpha_3_code": "PYF",
        "numeric_code": 258,
        "flag": "🇵🇫",
    },
    "TF": {
        "official_name": "French Southern Territories (the)",
        "name_en": "French Southern Territories",
        "name_ge": "საფრანგეთის სამხრეთ ტერიტორიები",
        "alpha_3_code": "ATF",
        "numeric_code": 260,
        "flag": "🇹🇫",
    },
    "GA": {
        "official_name": "Gabon",
        "name_en": "Gabon",
        "name_ge": "გაბონი",
        "alpha_3_code": "GAB",
        "numeric_code": 266,
        "flag": "🇬🇦",
    },
    "GM": {
        "official_name": "Gambia (the)",
        "name_en": "Gambia",
        "name_ge": "გამბია",
        "alpha_3_code": "GMB",
        "numeric_code": 270,
        "flag": "🇬🇲",
    },
    "GE": {
        "official_name": "Georgia",
        "name_en": "Georgia",
        "name_ge": "საქართველო",
        "alpha_3_code": "GEO",
        "numeric_code": 268,
        "flag": "🇬🇪",
    },
    "DE": {
        "official_name": "Germany",
        "name_en": "Germany",
        "name_ge": "გერმანია",
        "alpha_3_code": "DEU",
        "numeric_code": 276,
        "flag": "🇩🇪",
    },
    "GH": {
        "official_name": "Ghana",
        "name_en": "Ghana",
        "name_ge": "განა",
        "alpha_3_code": "GHA",
        "numeric_code": 288,
        "flag": "🇬🇭",
    },
    "GI": {
        "official_name": "Gibraltar",
        "name_en": "Gibraltar",
        "name_ge": "გიბრალტარი",
        "alpha_3_code": "GIB",
        "numeric_code": 292,
        "flag": "🇬🇮",
    },
    "GR": {
        "official_name": "Greece",
        "name_en": "Greece",
        "name_ge": "საბერძნეთი",
        "alpha_3_code": "GRC",
        "numeric_code": 300,
        "flag": "🇬🇷",
    },
    "GL": {
        "official_name": "Greenland",
        "name_en": "Greenland",
        "name_ge": "გრენლანდია",
        "alpha_3_code": "GRL",
        "numeric_code": 304,
        "flag": "🇬🇱",
    },
    "GD": {
        "official_name": "Grenada",
        "name_en": "Grenada",
        "name_ge": "გრენადა",
        "alpha_3_code": "GRD",
        "numeric_code": 308,
        "flag": "🇬🇩",
    },
    "GP": {
        "official_name": "Guadeloupe",
        "name_en": "Guadeloupe",
        "name_ge": "გვადელუპე",
        "alpha_3_code": "GLP",
        "numeric_code": 312,
        "flag": "🇬🇵",
    },
    "GU": {
        "official_name": "Guam",
        "name_en": "Guam",
        "name_ge": "გუამი",
        "alpha_3_code": "GUM",
        "numeric_code": 316,
        "flag": "🇬🇺",
    },
    "GT": {
        "official_name": "Guatemala",
        "name_en": "Guatemala",
        "name_ge": "გვატემალა",
        "alpha_3_code": "GTM",
        "numeric_code": 320,
        "flag": "🇬🇹",
    },
    "GG": {
        "official_name": "Guernsey",
        "name_en": "Guernsey",
        "name_ge": "გერნსი",
        "alpha_3_code": "GGY",
        "numeric_code": 831,
        "flag": "🇬🇬",
    },
    "GN": {
        "official_name": "Guinea",
        "name_en": "Guinea",
        "name_ge": "გვინეა",
        "alpha_3_code": "GIN",
        "numeric_code": 324,
        "flag": "🇬🇳",
    },
    "GW": {
        "official_name": "Guinea-Bissau",
        "name_en": "Guinea-Bissau",
        "name_ge": "გვინეა-ბისაუ",
        "alpha_3_code": "GNB",
        "numeric_code": 624,
        "flag": "🇬🇼",
    },
    "GY": {
        "official_name": "Guyana",
        "name_en": "Guyana",
        "name_ge": "გაიანა",
        "alpha_3_code": "GUY",
        "numeric_code": 328,
        "flag": "🇬🇾",
    },
    "HT": {
        "official_name": "Haiti",
        "name_en": "Haiti",
        "name_ge": "ჰაიტი",
        "alpha_3_code": "HTI",
        "numeric_code": 332,
        "flag": "🇭🇹",
    },
    "HM": {
        "official_name": "Heard Island and McDonald Islands",
        "name_en": "Heard Island and McDonald Islands",
        "name_ge": "ჰერდის კუნძული და მაკდონალდის კუნძულები",
        "alpha_3_code": "HMD",
        "numeric_code": 334,
        "flag": "🇭🇲",
    },
    "VA": {
        "official_name": "Holy See (the)",
        "name_en": "Holy See",
        "name_ge": "წმიდა საყდარი",
        "alpha_3_code": "VAT",
        "numeric_code": 336,
        "flag": None,
    },
    "HN": {
        "official_name": "Honduras",
        "name_en": "Honduras",
        "name_ge": "ჰონდურასი",
        "alpha_3_code": "HND",
        "numeric_code": 340,
        "flag": "🇭🇳",
    },
    "HK": {
        "official_name": "Hong Kong",
        "name_en": "Hong Kong",
        "name_ge": "ჰონგ კონგი",
        "alpha_3_code": "HKG",
        "numeric_code": 344,
        "flag": "🇭🇰",
    },
    "HU": {
        "official_name": "Hungary",
        "name_en": "Hungary",
        "name_ge": "უნგრეთი",
        "alpha_3_code": "HUN",
        "numeric_code": 348,
        "flag": "🇭🇺",
    },
    "IS": {
        "official_name": "Iceland",
        "name_en": "Iceland",
        "name_ge": "ისლანდია",
        "alpha_3_code": "ISL",
        "numeric_code": 352,
        "flag": "🇮🇸",
    },
    "IN": {
        "official_name": "India",
        "name_en": "India",
        "name_ge": "ინდოეთი",
        "alpha_3_code": "IND",
        "numeric_code": 356,
        "flag": "🇮🇳",
    },
    "ID": {
        "official_name": "Indonesia",
        "name_en": "Indonesia",
        "name_ge": "ინდონეზია",
        "alpha_3_code": "IDN",
        "numeric_code": 360,
        "flag": "🇮🇩",
    },
    "IR": {
        "official_name": "Iran (Islamic Republic of)",
        "name_en": "Iran",
        "name_ge": "ირანი",
        "alpha_3_code": "IRN",
        "numeric_code": 364,
        "flag": "🇮🇷",
    },
    "IQ": {
        "official_name": "Iraq",
        "name_en": "Iraq",
        "name_ge": "ერაყი",
        "alpha_3_code": "IRQ",
        "numeric_code": 368,
        "flag": "🇮🇶",
    },
    "IE": {
        "official_name": "Ireland",
        "name_en": "Ireland",
        "name_ge": "ირლანდია",
        "alpha_3_code": "IRL",
        "numeric_code": 372,
        "flag": "🇮🇪",
    },
    "IM": {
        "official_name": "Isle of Man",
        "name_en": "Isle of Man",
        "name_ge": "მენის კუნძული",
        "alpha_3_code": "IMN",
        "numeric_code": 833,
        "flag": "🇮🇲",
    },
    "IL": {
        "official_name": "Israel",
        "name_en": "Israel",
        "name_ge": "ისრაელი",
        "alpha_3_code": "ISR",
        "numeric_code": 376,
        "flag": "🇮🇱",
    },
    "IT": {
        "official_name": "Italy",
        "name_en": "Italy",
        "name_ge": "იტალია",
        "alpha_3_code": "ITA",
        "numeric_code": 380,
        "flag": "🇮🇹",
    },
    "JM": {
        "official_name": "Jamaica",
        "name_en": "Jamaica",
        "name_ge": "იამაიკა",
        "alpha_3_code": "JAM",
        "numeric_code": 388,
        "flag": "🇯🇲",
    },
    "JP": {
        "official_name": "Japan",
        "name_en": "Japan",
        "name_ge": "იაპონია",
        "alpha_3_code": "JPN",
        "numeric_code": 392,
        "flag": "🇯🇵",
    },
    "JE": {
        "official_name": "Jersey",
        "name_en": "Jersey",
        "name_ge": "ჯერსი",
        "alpha_3_code": "JEY",
        "numeric_code": 832,
        "flag": "🇯🇪",
    },
    "JO": {
        "official_name": "Jordan",
        "name_en": "Jordan",
        "name_ge": "ჟორდანია",
        "alpha_3_code": "JOR",
        "numeric_code": 400,
        "flag": "🇯🇴",
    },
    "KZ": {
        "official_name": "Kazakhstan",
        "name_en": "Kazakhstan",
        "name_ge": "ყაზახეთი",
        "alpha_3_code": "KAZ",
        "numeric_code": 398,
        "flag": "🇰🇿",
    },
    "KE": {
        "official_name": "Kenya",
        "name_en": "Kenya",
        "name_ge": "კენია",
        "alpha_3_code": "KEN",
        "numeric_code": 404,
        "flag": "🇰🇪",
    },
    "KI": {
        "official_name": "Kiribati",
        "name_en": "Kiribati",
        "name_ge": "კირიბატი",
        "alpha_3_code": "KIR",
        "numeric_code": 296,
        "flag": "🇰🇮",
    },
    "KP": {
        "official_name": "Korea (the Democratic People's Republic of)",
        "name_en": "Korea",
        "name_ge": "კორეა",
        "alpha_3_code": "PRK",
        "numeric_code": 408,
        "flag": "🇰🇵",
    },
    "KR": {
        "official_name": "Korea (the Republic of)",
        "name_en": "Korea",
        "name_ge": "კორეა",
        "alpha_3_code": "KOR",
        "numeric_code": 410,
        "flag": "🇰🇷",
    },
    "KW": {
        "official_name": "Kuwait",
        "name_en": "Kuwait",
        "name_ge": "ქუვეითი",
        "alpha_3_code": "KWT",
        "numeric_code": 414,
        "flag": "🇰🇼",
    },
    "KG": {
        "official_name": "Kyrgyzstan",
        "name_en": "Kyrgyzstan",
        "name_ge": "ყირგიზეთი",
        "alpha_3_code": "KGZ",
        "numeric_code": 417,
        "flag": "🇰🇬",
    },
    "LA": {
        "official_name": "Lao People's Democratic Republic (the)",
        "name_en": "Lao People's Democratic Republic",
        "name_ge": "ლაოს სახალხო დემოკრატიული რესპუბლიკა",
        "alpha_3_code": "LAO",
        "numeric_code": 418,
        "flag": "🇱🇦",
    },
    "LV": {
        "official_name": "Latvia",
        "name_en": "Latvia",
        "name_ge": "ლატვია",
        "alpha_3_code": "LVA",
        "numeric_code": 428,
        "flag": "🇱🇻",
    },
    "LB": {
        "official_name": "Lebanon",
        "name_en": "Lebanon",
        "name_ge": "ლიბანი",
        "alpha_3_code": "LBN",
        "numeric_code": 422,
        "flag": "🇱🇧",
    },
    "LS": {
        "official_name": "Lesotho",
        "name_en": "Lesotho",
        "name_ge": "ლესოტო",
        "alpha_3_code": "LSO",
        "numeric_code": 426,
        "flag": "🇱🇸",
    },
    "LR": {
        "official_name": "Liberia",
        "name_en": "Liberia",
        "name_ge": "ლიბერია",
        "alpha_3_code": "LBR",
        "numeric_code": 430,
        "flag": "🇱🇷",
    },
    "LY": {
        "official_name": "Libya",
        "name_en": "Libya",
        "name_ge": "ლიბია",
        "alpha_3_code": "LBY",
        "numeric_code": 434,
        "flag": "🇱🇾",
    },
    "LI": {
        "official_name": "Liechtenstein",
        "name_en": "Liechtenstein",
        "name_ge": "ლიხტენშტეინი",
        "alpha_3_code": "LIE",
        "numeric_code": 438,
        "flag": "🇱🇮",
    },
    "LT": {
        "official_name": "Lithuania",
        "name_en": "Lithuania",
        "name_ge": "ლიტვა",
        "alpha_3_code": "LTU",
        "numeric_code": 440,
        "flag": "🇱🇹",
    },
    "LU": {
        "official_name": "Luxembourg",
        "name_en": "Luxembourg",
        "name_ge": "ლუქსემბურგი",
        "alpha_3_code": "LUX",
        "numeric_code": 442,
        "flag": "🇱🇺",
    },
    "MO": {
        "official_name": "Macao",
        "name_en": "Macao",
        "name_ge": "მაკაო",
        "alpha_3_code": "MAC",
        "numeric_code": 446,
        "flag": "🇲🇴",
    },
    "MG": {
        "official_name": "Madagascar",
        "name_en": "Madagascar",
        "name_ge": "მადაგასკარი",
        "alpha_3_code": "MDG",
        "numeric_code": 450,
        "flag": "🇲🇬",
    },
    "MW": {
        "official_name": "Malawi",
        "name_en": "Malawi",
        "name_ge": "მალავი",
        "alpha_3_code": "MWI",
        "numeric_code": 454,
        "flag": "🇲🇼",
    },
    "MY": {
        "official_name": "Malaysia",
        "name_en": "Malaysia",
        "name_ge": "მალაიზია",
        "alpha_3_code": "MYS",
        "numeric_code": 458,
        "flag": "🇲🇾",
    },
    "MV": {
        "official_name": "Maldives",
        "name_en": "Maldives",
        "name_ge": "მალდივები",
        "alpha_3_code": "MDV",
        "numeric_code": 462,
        "flag": "🇲🇻",
    },
    "ML": {
        "official_name": "Mali",
        "name_en": "Mali",
        "name_ge": "მალი",
        "alpha_3_code": "MLI",
        "numeric_code": 466,
        "flag": "🇲🇱",
    },
    "MT": {
        "official_name": "Malta",
        "name_en": "Malta",
        "name_ge": "მალტა",
        "alpha_3_code": "MLT",
        "numeric_code": 470,
        "flag": "🇲🇹",
    },
    "MH": {
        "official_name": "Marshall Islands (the)",
        "name_en": "Marshall Islands",
        "name_ge": "მარშალის კუნძულები",
        "alpha_3_code": "MHL",
        "numeric_code": 584,
        "flag": "🇲🇭",
    },
    "MQ": {
        "official_name": "Martinique",
        "name_en": "Martinique",
        "name_ge": "მარტინიკი",
        "alpha_3_code": "MTQ",
        "numeric_code": 474,
        "flag": "🇲🇶",
    },
    "MR": {
        "official_name": "Mauritania",
        "name_en": "Mauritania",
        "name_ge": "მავრიტანია",
        "alpha_3_code": "MRT",
        "numeric_code": 478,
        "flag": "🇲🇷",
    },
    "MU": {
        "official_name": "Mauritius",
        "name_en": "Mauritius",
        "name_ge": "მავრიკი",
        "alpha_3_code": "MUS",
        "numeric_code": 480,
        "flag": "🇲🇺",
    },
    "YT": {
        "official_name": "Mayotte",
        "name_en": "Mayotte",
        "name_ge": "მაიოტა",
        "alpha_3_code": "MYT",
        "numeric_code": 175,
        "flag": "🇾🇹",
    },
    "MX": {
        "official_name": "Mexico",
        "name_en": "Mexico",
        "name_ge": "მექსიკა",
        "alpha_3_code": "MEX",
        "numeric_code": 484,
        "flag": "🇲🇽",
    },
    "FM": {
        "official_name": "Micronesia (Federated States of)",
        "name_en": "Micronesia",
        "name_ge": "მიკრონეზია",
        "alpha_3_code": "FSM",
        "numeric_code": 583,
        "flag": "🇫🇲",
    },
    "MD": {
        "official_name": "Moldova (the Republic of)",
        "name_en": "Moldova",
        "name_ge": "მოლდოვა",
        "alpha_3_code": "MDA",
        "numeric_code": 498,
        "flag": "🇲🇩",
    },
    "MC": {
        "official_name": "Monaco",
        "name_en": "Monaco",
        "name_ge": "მონაკო",
        "alpha_3_code": "MCO",
        "numeric_code": 492,
        "flag": "🇲🇨",
    },
    "MN": {
        "official_name": "Mongolia",
        "name_en": "Mongolia",
        "name_ge": "მონღოლეთი",
        "alpha_3_code": "MNG",
        "numeric_code": 496,
        "flag": "🇲🇳",
    },
    "ME": {
        "official_name": "Montenegro",
        "name_en": "Montenegro",
        "name_ge": "მონტენეგრო",
        "alpha_3_code": "MNE",
        "numeric_code": 499,
        "flag": "🇲🇪",
    },
    "MS": {
        "official_name": "Montserrat",
        "name_en": "Montserrat",
        "name_ge": "მონსერატი",
        "alpha_3_code": "MSR",
        "numeric_code": 500,
        "flag": "🇲🇸",
    },
    "MA": {
        "official_name": "Morocco",
        "name_en": "Morocco",
        "name_ge": "მაროკო",
        "alpha_3_code": "MAR",
        "numeric_code": 504,
        "flag": "🇲🇦",
    },
    "MZ": {
        "official_name": "Mozambique",
        "name_en": "Mozambique",
        "name_ge": "მოზამბიკი",
        "alpha_3_code": "MOZ",
        "numeric_code": 508,
        "flag": "🇲🇿",
    },
    "MM": {
        "official_name": "Myanmar",
        "name_en": "Myanmar (Burma)",
        "name_ge": "მიანმარი (ბირმა)",
        "alpha_3_code": "MMR",
        "numeric_code": 104,
        "flag": "🇲🇲",
    },
    "NA": {
        "official_name": "Namibia",
        "name_en": "Namibia",
        "name_ge": "ნამიბია",
        "alpha_3_code": "NAM",
        "numeric_code": 516,
        "flag": "🇳🇦",
    },
    "NR": {
        "official_name": "Nauru",
        "name_en": "Nauru",
        "name_ge": "ნაურუ",
        "alpha_3_code": "NRU",
        "numeric_code": 520,
        "flag": "🇳🇷",
    },
    "NP": {
        "official_name": "Nepal",
        "name_en": "Nepal",
        "name_ge": "ნეპალი",
        "alpha_3_code": "NPL",
        "numeric_code": 524,
        "flag": "🇳🇵",
    },
    "NL": {
        "official_name": "Netherlands (the)",
        "name_en": "Netherlands",
        "name_ge": "ნიდერლანდები",
        "alpha_3_code": "NLD",
        "numeric_code": 528,
        "flag": "🇳🇱",
    },
    "NC": {
        "official_name": "New Caledonia",
        "name_en": "New Caledonia",
        "name_ge": "ახალი კალედონია",
        "alpha_3_code": "NCL",
        "numeric_code": 540,
        "flag": "🇳🇨",
    },
    "NZ": {
        "official_name": "New Zealand",
        "name_en": "New Zealand",
        "name_ge": "Ახალი ზელანდია",
        "alpha_3_code": "NZL",
        "numeric_code": 554,
        "flag": "🇳🇿",
    },
    "NI": {
        "official_name": "Nicaragua",
        "name_en": "Nicaragua",
        "name_ge": "ნიკარაგუა",
        "alpha_3_code": "NIC",
        "numeric_code": 558,
        "flag": "🇳🇮",
    },
    "NE": {
        "official_name": "Niger (the)",
        "name_en": "Niger",
        "name_ge": "ნიგერი",
        "alpha_3_code": "NER",
        "numeric_code": 562,
        "flag": "🇳🇪",
    },
    "NG": {
        "official_name": "Nigeria",
        "name_en": "Nigeria",
        "name_ge": "ნიგერია",
        "alpha_3_code": "NGA",
        "numeric_code": 566,
        "flag": "🇳🇬",
    },
    "NU": {
        "official_name": "Niue",
        "name_en": "Niue",
        "name_ge": "ნიუე",
        "alpha_3_code": "NIU",
        "numeric_code": 570,
        "flag": "🇳🇺",
    },
    "NF": {
        "official_name": "Norfolk Island",
        "name_en": "Norfolk Island",
        "name_ge": "ნორფოლკის კუნძული",
        "alpha_3_code": "NFK",
        "numeric_code": 574,
        "flag": "🇳🇫",
    },
    "MK": {
        "official_name": "North Macedonia",
        "name_en": "North Macedonia",
        "name_ge": "ჩრდილოეთ მაკედონია",
        "alpha_3_code": "MKD",
        "numeric_code": 807,
        "flag": "🇲🇰",
    },
    "MP": {
        "official_name": "Northern Mariana Islands (the)",
        "name_en": "Northern Mariana Islands",
        "name_ge": "ჩრდილოეთ მარიანას კუნძულები",
        "alpha_3_code": "MNP",
        "numeric_code": 580,
        "flag": "🇲🇵",
    },
    "NO": {
        "official_name": "Norway",
        "name_en": "Norway",
        "name_ge": "ნორვეგია",
        "alpha_3_code": "NOR",
        "numeric_code": 578,
        "flag": "🇳🇴",
    },
    "OM": {
        "official_name": "Oman",
        "name_en": "Oman",
        "name_ge": "ომანი",
        "alpha_3_code": "OMN",
        "numeric_code": 512,
        "flag": "🇴🇲",
    },
    "PK": {
        "official_name": "Pakistan",
        "name_en": "Pakistan",
        "name_ge": "პაკისტანი",
        "alpha_3_code": "PAK",
        "numeric_code": 586,
        "flag": "🇵🇰",
    },
    "PW": {
        "official_name": "Palau",
        "name_en": "Palau",
        "name_ge": "პალაუ",
        "alpha_3_code": "PLW",
        "numeric_code": 585,
        "flag": "🇵🇼",
    },
    "PS": {
        "official_name": "Palestine, State of",
        "name_en": "Palestine",
        "name_ge": "პალესტინა",
        "alpha_3_code": "PSE",
        "numeric_code": 275,
        "flag": "🇵🇸",
    },
    "PA": {
        "official_name": "Panama",
        "name_en": "Panama",
        "name_ge": "პანამა",
        "alpha_3_code": "PAN",
        "numeric_code": 591,
        "flag": "🇵🇦",
    },
    "PG": {
        "official_name": "Papua New Guinea",
        "name_en": "Papua New Guinea",
        "name_ge": "პაპუა ახალი გვინეა",
        "alpha_3_code": "PNG",
        "numeric_code": 598,
        "flag": "🇵🇬",
    },
    "PY": {
        "official_name": "Paraguay",
        "name_en": "Paraguay",
        "name_ge": "პარაგვაი",
        "alpha_3_code": "PRY",
        "numeric_code": 600,
        "flag": "🇵🇾",
    },
    "PE": {
        "official_name": "Peru",
        "name_en": "Peru",
        "name_ge": "პერუ",
        "alpha_3_code": "PER",
        "numeric_code": 604,
        "flag": "🇵🇪",
    },
    "PH": {
        "official_name": "Philippines (the)",
        "name_en": "Philippines",
        "name_ge": "ფილიპინები",
        "alpha_3_code": "PHL",
        "numeric_code": 608,
        "flag": "🇵🇭",
    },
    "PN": {
        "official_name": "Pitcairn",
        "name_en": "Pitcairn",
        "name_ge": "პიტკერნი",
        "alpha_3_code": "PCN",
        "numeric_code": 612,
        "flag": "🇵🇳",
    },
    "PL": {
        "official_name": "Poland",
        "name_en": "Poland",
        "name_ge": "პოლონეთი",
        "alpha_3_code": "POL",
        "numeric_code": 616,
        "flag": "🇵🇱",
    },
    "PT": {
        "official_name": "Portugal",
        "name_en": "Portugal",
        "name_ge": "პორტუგალია",
        "alpha_3_code": "PRT",
        "numeric_code": 620,
        "flag": "🇵🇹",
    },
    "PR": {
        "official_name": "Puerto Rico",
        "name_en": "Puerto Rico",
        "name_ge": "პუერტო რიკო",
        "alpha_3_code": "PRI",
        "numeric_code": 630,
        "flag": "🇵🇷",
    },
    "QA": {
        "official_name": "Qatar",
        "name_en": "Qatar",
        "name_ge": "ყატარი",
        "alpha_3_code": "QAT",
        "numeric_code": 634,
        "flag": "🇶🇦",
    },
    "RO": {
        "official_name": "Romania",
        "name_en": "Romania",
        "name_ge": "რუმინეთი",
        "alpha_3_code": "ROU",
        "numeric_code": 642,
        "flag": "🇷🇴",
    },
    "RU": {
        "official_name": "Russian Federation (the)",
        "name_en": "Russia",
        "name_ge": "რუსეთი",
        "alpha_3_code": "RUS",
        "numeric_code": 643,
        "flag": "🇷🇺",
    },
    "RW": {
        "official_name": "Rwanda",
        "name_en": "Rwanda",
        "name_ge": "რუანდა",
        "alpha_3_code": "RWA",
        "numeric_code": 646,
        "flag": "🇷🇼",
    },
    "RE": {
        "official_name": "Réunion",
        "name_en": "Réunion",
        "name_ge": "რეიუნიონი",
        "alpha_3_code": "REU",
        "numeric_code": 638,
        "flag": "🇷🇪",
    },
    "BL": {
        "official_name": "Saint Barthélemy",
        "name_en": "Saint Barthélemy",
        "name_ge": "წმინდა ბართლემე",
        "alpha_3_code": "BLM",
        "numeric_code": 652,
        "flag": "🇧🇱",
    },
    "SH": {
        "official_name": "Saint Helena, Ascension and Tristan da Cunha",
        "name_en": "Saint Helena",
        "name_ge": "წმინდა ელენა",
        "alpha_3_code": "SHN",
        "numeric_code": 654,
        "flag": "🇸🇭",
    },
    "KN": {
        "official_name": "Saint Kitts and Nevis",
        "name_en": "Saint Kitts and Nevis",
        "name_ge": "სენტ კიტსი და ნევისი",
        "alpha_3_code": "KNA",
        "numeric_code": 659,
        "flag": "🇰🇳",
    },
    "LC": {
        "official_name": "Saint Lucia",
        "name_en": "Saint Lucia",
        "name_ge": "წმინდა ლუსია",
        "alpha_3_code": "LCA",
        "numeric_code": 662,
        "flag": "🇱🇨",
    },
    "MF": {
        "official_name": "Saint Martin (French part)",
        "name_en": "Saint Martin (French part)",
        "name_ge": "სენტ მარტინი (ფრანგული ნაწილი)",
        "alpha_3_code": "MAF",
        "numeric_code": 663,
        "flag": "🇲🇫",
    },
    "PM": {
        "official_name": "Saint Pierre and Miquelon",
        "name_en": "Saint Pierre and Miquelon",
        "name_ge": "სენტ პიერი და მიკელონი",
        "alpha_3_code": "SPM",
        "numeric_code": 666,
        "flag": "🇵🇲",
    },
    "VC": {
        "official_name": "Saint Vincent and the Grenadines",
        "name_en": "Saint Vincent and the Grenadines",
        "name_ge": "სენტ ვინსენტი და გრენადინები",
        "alpha_3_code": "VCT",
        "numeric_code": 670,
        "flag": "🇻🇨",
    },
    "WS": {
        "official_name": "Samoa",
        "name_en": "Samoa",
        "name_ge": "სამოა",
        "alpha_3_code": "WSM",
        "numeric_code": 882,
        "flag": "🇼🇸",
    },
    "SM": {
        "official_name": "San Marino",
        "name_en": "San Marino",
        "name_ge": "სან მარინო",
        "alpha_3_code": "SMR",
        "numeric_code": 674,
        "flag": "🇸🇲",
    },
    "ST": {
        "official_name": "Sao Tome and Principe",
        "name_en": "Sao Tome and Principe",
        "name_ge": "სან-ტომე და პრინსიპი",
        "alpha_3_code": "STP",
        "numeric_code": 678,
        "flag": "🇸🇹",
    },
    "SA": {
        "official_name": "Saudi Arabia",
        "name_en": "Saudi Arabia",
        "name_ge": "საუდის არაბეთი",
        "alpha_3_code": "SAU",
        "numeric_code": 682,
        "flag": "🇸🇦",
    },
    "SN": {
        "official_name": "Senegal",
        "name_en": "Senegal",
        "name_ge": "სენეგალი",
        "alpha_3_code": "SEN",
        "numeric_code": 686,
        "flag": "🇸🇳",
    },
    "RS": {
        "official_name": "Serbia",
        "name_en": "Serbia",
        "name_ge": "სერბეთი",
        "alpha_3_code": "SRB",
        "numeric_code": 688,
        "flag": "🇷🇸",
    },
    "SC": {
        "official_name": "Seychelles",
        "name_en": "Seychelles",
        "name_ge": "სეიშელის კუნძულები",
        "alpha_3_code": "SYC",
        "numeric_code": 690,
        "flag": "🇸🇨",
    },
    "SL": {
        "official_name": "Sierra Leone",
        "name_en": "Sierra Leone",
        "name_ge": "სიერა ლეონე",
        "alpha_3_code": "SLE",
        "numeric_code": 694,
        "flag": "🇸🇱",
    },
    "SG": {
        "official_name": "Singapore",
        "name_en": "Singapore",
        "name_ge": "სინგაპური",
        "alpha_3_code": "SGP",
        "numeric_code": 702,
        "flag": "🇸🇬",
    },
    "SX": {
        "official_name": "Sint Maarten (Dutch part)",
        "name_en": "Sint Maarten (Dutch part)",
        "name_ge": "სინტ მარტენი (ჰოლანდიური ნაწილი)",
        "alpha_3_code": "SXM",
        "numeric_code": 534,
        "flag": "🇸🇽",
    },
    "SK": {
        "official_name": "Slovakia",
        "name_en": "Slovakia",
        "name_ge": "სლოვაკეთი",
        "alpha_3_code": "SVK",
        "numeric_code": 703,
        "flag": "🇸🇰",
    },
    "SI": {
        "official_name": "Slovenia",
        "name_en": "Slovenia",
        "name_ge": "სლოვენია",
        "alpha_3_code": "SVN",
        "numeric_code": 705,
        "flag": "🇸🇮",
    },
    "SB": {
        "official_name": "Solomon Islands",
        "name_en": "Solomon Islands",
        "name_ge": "სოლომონის კუნძულები",
        "alpha_3_code": "SLB",
        "numeric_code": 90,
        "flag": "🇸🇧",
    },
    "SO": {
        "official_name": "Somalia",
        "name_en": "Somalia",
        "name_ge": "სომალი",
        "alpha_3_code": "SOM",
        "numeric_code": 706,
        "flag": "🇸🇴",
    },
    "ZA": {
        "official_name": "South Africa",
        "name_en": "South Africa",
        "name_ge": "სამხრეთ აფრიკა",
        "alpha_3_code": "ZAF",
        "numeric_code": 710,
        "flag": "🇿🇦",
    },
    "GS": {
        "official_name": "South Georgia and the South Sandwich Islands",
        "name_en": "South Georgia and the South Sandwich Islands",
        "name_ge": "სამხრეთ ჯორჯია და სამხრეთ სენდვიჩის კუნძულები",
        "alpha_3_code": "SGS",
        "numeric_code": 239,
        "flag": "🇬🇸",
    },
    "SS": {
        "official_name": "South Sudan",
        "name_en": "South Sudan",
        "name_ge": "სამხრეთ სუდანი",
        "alpha_3_code": "SSD",
        "numeric_code": 728,
        "flag": "🇸🇸",
    },
    "ES": {
        "official_name": "Spain",
        "name_en": "Spain",
        "name_ge": "ესპანეთი",
        "alpha_3_code": "ESP",
        "numeric_code": 724,
        "flag": "🇪🇸",
    },
    "LK": {
        "official_name": "Sri Lanka",
        "name_en": "Sri Lanka",
        "name_ge": "შრი ლანკა",
        "alpha_3_code": "LKA",
        "numeric_code": 144,
        "flag": "🇱🇰",
    },
    "SD": {
        "official_name": "Sudan (the)",
        "name_en": "Sudan",
        "name_ge": "სუდანი",
        "alpha_3_code": "SDN",
        "numeric_code": 729,
        "flag": "🇸🇩",
    },
    "SR": {
        "official_name": "Suriname",
        "name_en": "Suriname",
        "name_ge": "სურინამი",
        "alpha_3_code": "SUR",
        "numeric_code": 740,
        "flag": "🇸🇷",
    },
    "SJ": {
        "official_name": "Svalbard and Jan Mayen",
        "name_en": "Svalbard and Jan Mayen",
        "name_ge": "სვალბარდი და იან მაიენი",
        "alpha_3_code": "SJM",
        "numeric_code": 744,
        "flag": "🇸🇯",
    },
    "SE": {
        "official_name": "Sweden",
        "name_en": "Sweden",
        "name_ge": "შვედეთი",
        "alpha_3_code": "SWE",
        "numeric_code": 752,
        "flag": "🇸🇪",
    },
    "CH": {
        "official_name": "Switzerland",
        "name_en": "Switzerland",
        "name_ge": "შვეიცარია",
        "alpha_3_code": "CHE",
        "numeric_code": 756,
        "flag": "🇨🇭",
    },
    "SY": {
        "official_name": "Syrian Arab Republic (the)",
        "name_en": "Syria",
        "name_ge": "სირია",
        "alpha_3_code": "SYR",
        "numeric_code": 760,
        "flag": "🇸🇾",
    },
    "TW": {
        "official_name": "Taiwan (Province of China)",
        "name_en": "Taiwan",
        "name_ge": "ტაივანი",
        "alpha_3_code": "TWN",
        "numeric_code": 158,
        "flag": "🇹🇼",
    },
    "TJ": {
        "official_name": "Tajikistan",
        "name_en": "Tajikistan",
        "name_ge": "ტაჯიკეთი",
        "alpha_3_code": "TJK",
        "numeric_code": 762,
        "flag": "🇹🇯",
    },
    "TZ": {
        "official_name": "Tanzania, the United Republic of",
        "name_en": "Tanzania",
        "name_ge": "ტანზანია",
        "alpha_3_code": "TZA",
        "numeric_code": 834,
        "flag": "🇹🇿",
    },
    "TH": {
        "official_name": "Thailand",
        "name_en": "Thailand",
        "name_ge": "ტაილანდი",
        "alpha_3_code": "THA",
        "numeric_code": 764,
        "flag": "🇹🇭",
    },
    "TL": {
        "official_name": "Timor-Leste",
        "name_en": "Timor-Leste",
        "name_ge": "ტიმორ-ლესტე",
        "alpha_3_code": "TLS",
        "numeric_code": 626,
        "flag": "🇹🇱",
    },
    "TG": {
        "official_name": "Togo",
        "name_en": "Togo",
        "name_ge": "ტოგო",
        "alpha_3_code": "TGO",
        "numeric_code": 768,
        "flag": "🇹🇬",
    },
    "TK": {
        "official_name": "Tokelau",
        "name_en": "Tokelau",
        "name_ge": "ტოკელაუ",
        "alpha_3_code": "TKL",
        "numeric_code": 772,
        "flag": "🇹🇰",
    },
    "TO": {
        "official_name": "Tonga",
        "name_en": "Tonga",
        "name_ge": "ტონგა",
        "alpha_3_code": "TON",
        "numeric_code": 776,
        "flag": "🇹🇴",
    },
    "TT": {
        "official_name": "Trinidad and Tobago",
        "name_en": "Trinidad and Tobago",
        "name_ge": "ტრინიდადი და ტობაგო",
        "alpha_3_code": "TTO",
        "numeric_code": 780,
        "flag": "🇹🇹",
    },
    "TN": {
        "official_name": "Tunisia",
        "name_en": "Tunisia",
        "name_ge": "ტუნისი",
        "alpha_3_code": "TUN",
        "numeric_code": 788,
        "flag": "🇹🇳",
    },
    "TR": {
        "official_name": "Turkey",
        "name_en": "Turkey",
        "name_ge": "თურქეთი",
        "alpha_3_code": "TUR",
        "numeric_code": 792,
        "flag": "🇹🇷",
    },
    "TM": {
        "official_name": "Turkmenistan",
        "name_en": "Turkmenistan",
        "name_ge": "თურქმენეთი",
        "alpha_3_code": "TKM",
        "numeric_code": 795,
        "flag": "🇹🇲",
    },
    "TC": {
        "official_name": "Turks and Caicos Islands (the)",
        "name_en": "Turks and Caicos Islands",
        "name_ge": "ტერქსისა და კაიკოსის კუნძულები",
        "alpha_3_code": "TCA",
        "numeric_code": 796,
        "flag": "🇹🇨",
    },
    "TV": {
        "official_name": "Tuvalu",
        "name_en": "Tuvalu",
        "name_ge": "ტუვალუ",
        "alpha_3_code": "TUV",
        "numeric_code": 798,
        "flag": "🇹🇻",
    },
    "UG": {
        "official_name": "Uganda",
        "name_en": "Uganda",
        "name_ge": "უგანდა",
        "alpha_3_code": "UGA",
        "numeric_code": 800,
        "flag": "🇺🇬",
    },
    "UA": {
        "official_name": "Ukraine",
        "name_en": "Ukraine",
        "name_ge": "უკრაინა",
        "alpha_3_code": "UKR",
        "numeric_code": 804,
        "flag": "🇺🇦",
    },
    "AE": {
        "official_name": "United Arab Emirates (the)",
        "name_en": "United Arab Emirates",
        "name_ge": "არაბთა გაერთიანებული საამიროები",
        "alpha_3_code": "ARE",
        "numeric_code": 784,
        "flag": "🇦🇪",
    },
    "GB": {
        "official_name": "United Kingdom of Great Britain and Northern Ireland (the)",
        "name_en": "Great Britain",
        "name_ge": "დიდი ბრიტანეთი",
        "alpha_3_code": "GBR",
        "numeric_code": 826,
        "flag": "🇬🇧",
    },
    "UM": {
        "official_name": "United States Minor Outlying Islands (the)",
        "name_en": "United States Minor Outlying Islands",
        "name_ge": "შეერთებული შტატების მცირე დაშორებული კუნძულები",
        "alpha_3_code": "UMI",
        "numeric_code": 581,
        "flag": "🇺🇲",
    },
    "US": {
        "official_name": "United States of America (the)",
        "name_en": "United States of America",
        "name_ge": "ამერიკის შეერთებული შტატები",
        "alpha_3_code": "USA",
        "numeric_code": 840,
        "flag": "🇺🇸",
    },
    "UY": {
        "official_name": "Uruguay",
        "name_en": "Uruguay",
        "name_ge": "ურუგვაი",
        "alpha_3_code": "URY",
        "numeric_code": 858,
        "flag": "🇺🇾",
    },
    "UZ": {
        "official_name": "Uzbekistan",
        "name_en": "Uzbekistan",
        "name_ge": "უზბეკეთი",
        "alpha_3_code": "UZB",
        "numeric_code": 860,
        "flag": "🇺🇿",
    },
    "VU": {
        "official_name": "Vanuatu",
        "name_en": "Vanuatu",
        "name_ge": "ვანუატუ",
        "alpha_3_code": "VUT",
        "numeric_code": 548,
        "flag": "🇻🇺",
    },
    "VE": {
        "official_name": "Venezuela (Bolivarian Republic of)",
        "name_en": "Venezuela",
        "name_ge": "ვენესუელა",
        "alpha_3_code": "VEN",
        "numeric_code": 862,
        "flag": "🇻🇪",
    },
    "VN": {
        "official_name": "Viet Nam",
        "name_en": "Viet Nam",
        "name_ge": "ვიეტნამი",
        "alpha_3_code": "VNM",
        "numeric_code": 704,
        "flag": "🇻🇳",
    },
    "VG": {
        "official_name": "Virgin Islands (British)",
        "name_en": "Virgin Islands (British)",
        "name_ge": "ვირჯინიის კუნძულები (ბრიტანული)",
        "alpha_3_code": "VGB",
        "numeric_code": 92,
        "flag": "🇻🇬",
    },
    "VI": {
        "official_name": "Virgin Islands (U.S.)",
        "name_en": "Virgin Islands (U.S.)",
        "name_ge": "ვირჯინიის კუნძულები (აშშ)",
        "alpha_3_code": "VIR",
        "numeric_code": 850,
        "flag": "🇻🇮",
    },
    "WF": {
        "official_name": "Wallis and Futuna",
        "name_en": "Wallis and Futuna",
        "name_ge": "უოლისი და ფუტუნა",
        "alpha_3_code": "WLF",
        "numeric_code": 876,
        "flag": "🇼🇫",
    },
    "EH": {
        "official_name": "Western Sahara",
        "name_en": "Western Sahara",
        "name_ge": "დასავლეთ საჰარა",
        "alpha_3_code": "ESH",
        "numeric_code": 732,
        "flag": "🇪🇭",
    },
    "YE": {
        "official_name": "Yemen",
        "name_en": "Yemen",
        "name_ge": "იემენი",
        "alpha_3_code": "YEM",
        "numeric_code": 887,
        "flag": "🇾🇪",
    },
    "ZM": {
        "official_name": "Zambia",
        "name_en": "Zambia",
        "name_ge": "ზამბია",
        "alpha_3_code": "ZMB",
        "numeric_code": 894,
        "flag": "🇿🇲",
    },
    "ZW": {
        "official_name": "Zimbabwe",
        "name_en": "Zimbabwe",
        "name_ge": "ზიმბაბვე",
        "alpha_3_code": "ZWE",
        "numeric_code": 716,
        "flag": "🇿🇼",
    },
    "AX": {
        "official_name": "Åland Islands",
        "name_en": "Åland Islands",
        "name_ge": "ალანდის კუნძულები",
        "alpha_3_code": "ALA",
        "numeric_code": 248,
        "flag": "🇦🇽",
    },
}


def get_country_meta_info_with_iso2_code(alpha_2_code):
    """
    Get country iso 2 code and return useful meta information.

    Example result structure for Israel(allpha_2_code="IL"):

    {
        "official_name": "Israel",
        "name_en": "Israel",
        "name_ge": "ისრაელი",
        "alpha_3_code": "ISR",
        "numeric_code": 376,
        "flag": "🇮🇱",
    }

    if given alpha_2_code not found, None will be returned.
    """
    return DATA.get(alpha_2_code)
