{
    # Tbilisi
    "თბილისი": {
        "name_ge": "თბილისი",
        "name_en": "Tbilisi",
        "region_ge": "თბილისი",  # actually მუნიციპალიტეტი, but anyways
        "region_en": "Tbilisi",  # actually მუნიციპალიტეტი, but anyways
        "is_region_center": 1,
        "population_in_thousands": 1201.8,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "აჭარა"
    "ბათუმი": {
        "name_ge": "ბათუმი",
        "name_en": "Batumi",
        "region_ge": "აჭარა",
        "region_en": "Adjara",
        "is_region_center": 1,
        "population_in_thousands": 173.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ქობულეთი": {
        "name_ge": "ქობულეთი",
        "name_en": "Kobuleti",
        "region_ge": "აჭარა",
        "region_en": "Adjara",
        "is_region_center": 0,
        "population_in_thousands": 28.3,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ხელვაჩაური": {
        "name_ge": "ხელვაჩაური",
        "name_en": "Khelvachauri",
        "region_ge": "აჭარა",
        "region_en": "Adjara",
        "is_region_center": 0,
        "population_in_thousands": 6.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ხულო": {
        "name_ge": "ხულო",
        "name_en": "Khulo",
        "region_ge": "აჭარა",
        "region_en": "Adjara",
        "is_region_center": 0,
        "population_in_thousands": 0.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "შუახევი": {
        "name_ge": "შუახევი",
        "name_en": "Shuakhevi",
        "region_ge": "აჭარა",
        "region_en": "Adjara",
        "is_region_center": 0,
        "population_in_thousands": 0.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ქედა": {
        "name_ge": "ქედა",
        "name_en": "Keda",
        "region_ge": "აჭარა",
        "region_en": "Adjara",
        "is_region_center": 0,
        "population_in_thousands": 1.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "აფხაზეთი"
    "სოხუმი": {
        "name_ge": "სოხუმი",
        "name_en": "Sokhumi",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 1,
        "population_in_thousands": 65.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ტყვარჩელი": {
        "name_ge": "ტყვარჩელი",
        "name_en": "Tkvarcheli",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 4.8,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ოჩამჩირე": {
        "name_ge": "ოჩამჩირე",
        "name_en": "Ochamchire",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 5.3,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "გუდაუთა": {
        "name_ge": "გუდაუთა",
        "name_en": "Gudauta",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 8.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "გალი": {
        "name_ge": "გალი",
        "name_en": "Gali",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 7.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "გულრიფში": {
        "name_ge": "გულრიფში",
        "name_en": "Gulripshi",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 3.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ბიჭვინთა": {
        "name_ge": "ბიჭვინთა",
        "name_en": "Bichvinta",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 4.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "გაგრა": {
        "name_ge": "გაგრა",
        "name_en": "Gagra",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 12,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ახალი ათონი": {
        "name_ge": "ახალი ათონი",
        "name_en": "Akhali Atoni",
        "region_ge": "აფხაზეთი",
        "region_en": "Abkhazia",
        "is_region_center": 0,
        "population_in_thousands": 1.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "გურია  "
    "ოზურგეთი": {
        "name_ge": "ოზურგეთი",
        "name_en": "Ozurgeti",
        "region_ge": "Guria",
        "region_en": "გურია",
        "is_region_center": 1,
        "population_in_thousands": 14.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ჩოხატაური": {
        "name_ge": "ჩოხატაური",
        "name_en": "Chokhatauri",
        "region_ge": "Guria",
        "region_en": "გურია",
        "is_region_center": 0,
        "population_in_thousands": 1.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ლანჩხუთი": {
        "name_ge": "ლანჩხუთი",
        "name_en": "Lanchkhuti",
        "region_ge": "Guria",
        "region_en": "გურია",
        "is_region_center": 0,
        "population_in_thousands": 6.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "იმერეთი"
    "ქუთაისი": {
        "name_ge": "ქუთაისი",
        "name_en": "Kutaisi",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 1,
        "population_in_thousands": 129.3,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "სამტრედია": {
        "name_ge": "სამტრედია",
        "name_en": "Samtredia",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 22.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ჭიათურა": {
        "name_ge": "ჭიათურა",
        "name_en": "Chiatura",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 12.3,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ხარაგაული": {
        "name_ge": "ხარაგაული",
        "name_en": "Kharagauli",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 1.8,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ზესტაფონი": {
        "name_ge": "ზესტაფონი",
        "name_en": "Zestafoni",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 20.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ტყიბული": {
        "name_ge": "ტყიბული",
        "name_en": "Tkibuli",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 8.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "წყალტუბო": {
        "name_ge": "წყალტუბო",
        "name_en": "Tskaltubo",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 8.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ხონი": {
        "name_ge": "ხონი",
        "name_en": "Khoni",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 8.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "საჩხერე": {
        "name_ge": "საჩხერე",
        "name_en": "Sachkhere",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 5.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ვანი": {
        "name_ge": "ვანი",
        "name_en": "Vani",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 3.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "თერჯოლა": {
        "name_ge": "თერჯოლა",
        "name_en": "Terjola",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 4.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ბაღდათი": {
        "name_ge": "ბაღდათი",
        "name_en": "Baghdati",
        "region_ge": "იმერეთი",
        "region_en": "Imereti",
        "is_region_center": 0,
        "population_in_thousands": 2.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "კახეთი "
    "თელავი": {
        "name_ge": "თელავი",
        "name_en": "Telavi",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 1,
        "population_in_thousands": 19.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "საგარეჯო": {
        "name_ge": "საგარეჯო",
        "name_en": "Sagarejo",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 10.3,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "გურჯაანი": {
        "name_ge": "გურჯაანი",
        "name_en": "Gurjaani",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 7.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ყვარელი": {
        "name_ge": "ყვარელი",
        "name_en": "Kvareli",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 9.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "დედოფლისწყარო": {
        "name_ge": "დედოფლისწყარო",
        "name_en": "Dedoplis Tskaro",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 5.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ლაგოდეხი": {
        "name_ge": "ლაგოდეხი",
        "name_en": "Lagodekhi",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 5.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ახმეტა": {
        "name_ge": "ახმეტა",
        "name_en": "Akhmeta",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 6.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "სიღნაღი": {
        "name_ge": "სიღნაღი",
        "name_en": "Sighnaghi",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 1.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "წნორი": {
        "name_ge": "წნორი",
        "name_en": "Tsnori",
        "region_ge": "კახეთი",
        "region_en": "Kakheti",
        "is_region_center": 0,
        "population_in_thousands": 4.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "მცხეთა-მთიანეთი"
    "მცხეთა": {
        "name_ge": "მცხეთა",
        "name_en": "Mtskheta",
        "region_ge": "მცხეთა-მთიანეთი",
        "region_en": "Mtskheta-Mtianeti",
        "is_region_center": 1,
        "population_in_thousands": 7.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "დუშეთი": {
        "name_ge": "დუშეთი",
        "name_en": "Dusheti",
        "region_ge": "მცხეთა-მთიანეთი",
        "region_en": "Mtskheta-Mtianeti",
        "is_region_center": 0,
        "population_in_thousands": 6.8,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ჟინვალი": {
        "name_ge": "ჟინვალი",
        "name_en": "Zhinvali",
        "region_ge": "მცხეთა-მთიანეთი",
        "region_en": "Mtskheta-Mtianeti",
        "is_region_center": 0,
        "population_in_thousands": 2.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ფასანაური": {
        "name_ge": "ფასანაური",
        "name_en": "Pasanauri",
        "region_ge": "მცხეთა-მთიანეთი",
        "region_en": "Mtskheta-Mtianeti",
        "is_region_center": 0,
        "population_in_thousands": 1.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ყაზბეგი": {
        "name_ge": "ყაზბეგი",
        "name_en": "Kazbegi",
        "region_ge": "მცხეთა-მთიანეთი",
        "region_en": "Mtskheta-Mtianeti",
        "is_region_center": 0,
        "population_in_thousands": 1.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "გუდაური": {
        "name_ge": "გუდაური",
        "name_en": "Gudauri",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 0.05,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "სტეფანწმინდა": {
        "name_ge": "სტეფანწმინდა",
        "name_en": "Stepantsminda",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 1.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "რაჭა-ლეჩხუმი და ქვემო სვანეთი"
    "ამბროლაური": {
        "name_ge": "ამბროლაური",
        "name_en": "Ambrolauri",
        "region_ge": "რაჭა-ლეჩხუმი და ქვემო სვანეთი",
        "region_en": "Racha-Lechkhumi and Lower Svaneti",
        "is_region_center": 1,
        "population_in_thousands": 2.0,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ონი": {
        "name_ge": "ონი",
        "name_en": "Oni",
        "region_ge": "რაჭა-ლეჩხუმი და ქვემო სვანეთი",
        "region_en": "Racha-Lechkhumi and Lower Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 2.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ლენტეხი": {
        "name_ge": "ლენტეხი",
        "name_en": "Lentekhi",
        "region_ge": "რაჭა-ლეჩხუმი და ქვემო სვანეთი",
        "region_en": "Racha-Lechkhumi and Lower Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ცაგერი": {
        "name_ge": "ცაგერი",
        "name_en": "Tsageri",
        "region_ge": "რაჭა-ლეჩხუმი და ქვემო სვანეთი",
        "region_en": "Racha-Lechkhumi and Lower Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 1.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "სამეგრელო-ზემო სვანეთი"
    "ზუგდიდი": {
        "name_ge": "ზუგდიდი",
        "name_en": "Zugdidi",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 1,
        "population_in_thousands": 41.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ფოთი": {
        "name_ge": "ფოთი",
        "name_en": "Poti",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 41.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "სენაკი": {
        "name_ge": "სენაკი",
        "name_en": "Senaki",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 17.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ჩხოროწყუ": {
        "name_ge": "ჩხოროწყუ",
        "name_en": "Chkhorotsku",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 2.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "აბაშა": {
        "name_ge": "აბაშა",
        "name_en": "Abasha",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 4.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "წალენჯიხა": {
        "name_ge": "წალენჯიხა",
        "name_en": "Tsalenjikha",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 3.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ხობი": {
        "name_ge": "ხობი",
        "name_en": "Khobi",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 3.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "მარტვილი": {
        "name_ge": "მარტვილი",
        "name_en": "Martvili",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 4.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ჯვარი": {
        "name_ge": "ჯვარი",
        "name_en": "Jvari",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 1.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "მესტია": {
        "name_ge": "მესტია",
        "name_en": "Mestia",
        "region_ge": "სამეგრელო-ზემო სვანეთი",
        "region_en": "Samegrelo-Zemo Svaneti",
        "is_region_center": 0,
        "population_in_thousands": 1.8,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "სამცხე-ჯავახეთი"
    "ახალციხე": {
        "name_ge": "ახალციხე",
        "name_en": "Akhaltsikhe",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 1,
        "population_in_thousands": 16.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ბორჯომი": {
        "name_ge": "ბორჯომი",
        "name_en": "Borjomi",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 15.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ასპინძა": {
        "name_ge": "ასპინძა",
        "name_en": "Aspindza",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 2.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ახალქალაქი": {
        "name_ge": "ახალქალაქი",
        "name_en": "Akhalkalaki",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 7.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ნინოწმინდა": {
        "name_ge": "ნინოწმინდა",
        "name_en": "Ninotsminda",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 4.3,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ვალე": {
        "name_ge": "ვალე",
        "name_en": "Vale",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 5.1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "აბასთუმანი": {
        "name_ge": "აბასთუმანი",
        "name_en": "Abastumani",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 0.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ადიგენი": {
        "name_ge": "ადიგენი",
        "name_en": "Adigeni",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 1,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ბაკურიანი": {
        "name_ge": "ბაკურიანი",
        "name_en": "Bakuriani",
        "region_ge": "სამცხე-ჯავახეთი",
        "region_en": "Samtskhe-Javakheti",
        "is_region_center": 0,
        "population_in_thousands": 1.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "ქვემო ქართლი"
    "რუსთავი": {
        "name_ge": "რუსთავი",
        "name_en": "Rustavi",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 1,
        "population_in_thousands": 128.8,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "მარნეული": {
        "name_ge": "მარნეული",
        "name_en": "Marneuli",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 23.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "გარდაბანი": {
        "name_ge": "გარდაბანი",
        "name_en": "Gardabani",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 11.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "დმანისი": {
        "name_ge": "დმანისი",
        "name_en": "Dmanisi",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 2.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "კაზრეთი": {
        "name_ge": "კაზრეთი",
        "name_en": "Kazreti",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 5.5,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ბოლნისი": {
        "name_ge": "ბოლნისი",
        "name_en": "Bolnisi",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 8.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "თეთრი წყარო": {
        "name_ge": "თეთრი წყარო",
        "name_en": "Tetri Tskaro",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 4.0,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "მანგლისი": {
        "name_ge": "მანგლისი",
        "name_en": "Manglisi",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 1.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "წალკა": {
        "name_ge": "წალკა",
        "name_en": "Tsalka",
        "region_ge": "ქვემო ქართლი",
        "region_en": "Kvemo Kartli",
        "is_region_center": 0,
        "population_in_thousands": 3.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    # "შიდა ქართლი"
    "გორი": {
        "name_ge": "გორი",
        "name_en": "Gori",
        "region_ge": "შიდა ქართლი",
        "region_en": "Shida Kartli",
        "is_region_center": 1,
        "population_in_thousands": 45.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ხაშური": {
        "name_ge": "ხაშური",
        "name_en": "Khashuri",
        "region_ge": "შიდა ქართლი",
        "region_en": "Shida Kartli",
        "is_region_center": 0,
        "population_in_thousands": 24.6,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "სურამი": {
        "name_ge": "სურამი",
        "name_en": "Surami",
        "region_ge": "შიდა ქართლი",
        "region_en": "Shida Kartli",
        "is_region_center": 0,
        "population_in_thousands": 7.4,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "აგარა": {
        "name_ge": "აგარა",
        "name_en": "Agara",
        "region_ge": "შიდა ქართლი",
        "region_en": "Shida Kartli",
        "is_region_center": 0,
        "population_in_thousands": 2.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "კასპი": {
        "name_ge": "კასპი",
        "name_en": "Kaspi",
        "region_ge": "შიდა ქართლი",
        "region_en": "Shida Kartli",
        "is_region_center": 0,
        "population_in_thousands": 12.7,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ქარელი": {
        "name_ge": "ქარელი",
        "name_en": "Kareli",
        "region_ge": "შიდა ქართლი",
        "region_en": "Shida Kartli",
        "is_region_center": 0,
        "population_in_thousands": 6.9,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
    "ცხინვალი": {
        "name_ge": "ცხინვალი",
        "name_en": "Tskhinvali",
        "region_ge": "შიდა ქართლი",
        "region_en": "Shida Kartli",
        "is_region_center": 0,
        "population_in_thousands": 32.2,
        "coordinates_lat_lon": [
            41.41,
            42.42,
        ],
    },
}
